arrow
pyyaml
pytz
-e git+https://github.com/cat-bro/ephemeris.git@release_0.10.7_plus_galaxywait_fix#egg=ephemeris
bioblend>=0.13.0
planemo==0.72.0

# requirements for galaxy virtualenv also required here for tests to run correctly
pysam==0.16.0.1
h5py==3.1.0
